### ISSUE TITLE
为什么不能用cnpm ？使用cnpm 报header-bg 没有定义

### ISSUE THREAD

**Issue by jinbiaoGu** [artiely/vue-admin#5]

**Comment by artiely** [comment]
这个与cnpm没有直接的关系，建议使用淘宝源，可以下载nrm工具进行源管理。

**Comment by jinbiaoGu** [comment]
使用cnpm install ,编译不通过 ，npm install 可以编译通过


----- 原始邮件 -----
发件人：artiely <notifications@github.com>
收件人：artiely/vue-admin <vue-admin@noreply.github.com>
抄送人：谷大麦 <gjb91@sina.com>,  State change <state_change@noreply.github.com>
主题：Re:_[artiely/vue-admin]_为什么不能用cnpm_？使用cnpm_报header-bg_没有定义_(#5)
日期：2020年09月14日 14点08分



这个与cnpm没有直接的关系，建议使用淘宝源，可以下载nrm工具进行源管理。
